### ISSUE TITLE
Remove the tests folder from UPM releases

### ISSUE THREAD

**Issue by TCROC** [TCROC/Mirror-UPM#1]
The Test folder is incorrectly being included in UPM releases.  Add that to the list of ignored folders

**Comment by alesmasiar** [comment]
Hi, I just found out you have a Mirror-UPM port as well ... amazing. I would love to use this, but in my project I have a dll conflicting with one in the Mirror Test folder, hence this issue is actually relevant for me. Is this solvable?

**Comment by TCROC** [comment]
@alesmasiar Hey sorry that it took so long for me to get back with you.  Ya this is solvable.  I'll get right on it.  Got caught up in other projects

**Comment by TCROC** [comment]
@alesmasiar I'm going to start testing the fix, so the upm tags will briefly go offline

**Comment by TCROC** [comment]
@alesmasiar It is re-releasing all of the tags without the Tests folder.  Let me know if that resolves your issue.  Thanks for reporting btw! :)

**Comment by alesmasiar** [comment]
No worries, I got other stuff to do. I've tried it just now a seems to be working fine, thanks 👍. 

Have you thought about adding these repos to OpenUPM? Maybe you'd manage to get some traction there. I think this might be helpful for more people, that prefer UPM to Asset Store.

Anyways, good work a thanks for the fixes.

**Comment by TCROC** [comment]
I like the idea of OpenUPM for this!  I'll open up a feature request for it. :)
