### ISSUE TITLE
Missing latest releases from Mirror repo

### ISSUE THREAD

**Issue by alesmasiar** [TCROC/Mirror-UPM#4]
Hey, it's me again. I wanted to update to the latest mirror (30.5.0), but this repo is missing few of the latest releases (since 30.4.2). Does it take a while to update or is there an issue?

**Comment by TCROC** [comment]
Thanks for the heads up.  I'll fix that :+1:

**Comment by TCROC** [comment]
It should be working again.

**Comment by alesmasiar** [comment]
Great, thanks a lot :)
